// Evaluates the design's `D` data object (services, copy, reviews...) and writes src/data/{services,site}.js
// with image paths already resolved to /img/*.webp. Hand-written constants live in src/data/links.js.
import fs from 'node:fs'
import path from 'node:path'

const ROOT = path.resolve(import.meta.dirname, '..')
const script = fs.readFileSync(path.join(ROOT, 'design-src', 'page-script.js'), 'utf8')
const start = script.indexOf('D = (() => {')
const end = script.indexOf('\n  })();', start)
if (start < 0 || end < 0) throw new Error('could not locate the D data block')
const D = new Function(`return (${script.slice(start + 4, end + '\n  })()'.length)})`)()

const img = (p) => (typeof p === 'string' && p.startsWith('assets/') ? '/img/' + p.slice(7).replace(/\.(png|jpe?g)$/i, '.webp') : p)

const services = {}
for (const tab of ['home', 'car', 'laundry']) {
  services[tab] = D[tab].map((s) => ({
    key: s.key,
    cat: s.cat,
    name: s.name,
    price: s.price,
    desc: s.desc,
    about: s.about,
    img: img(s.img),
    cardImg: img(s.cardImg),
    wa: s.wa,
  }))
}

const json = (v) => JSON.stringify(v, null, 2)
const banner = '// Generated by tools/extract-data.mjs from the Claude Design export. Edit freely after the port.\n'

fs.mkdirSync(path.join(ROOT, 'src', 'data'), { recursive: true })
fs.writeFileSync(
  path.join(ROOT, 'src', 'data', 'services.js'),
  banner +
    `export const SERVICES = ${json(services)}\n\n` +
    `export const TABS = [\n  { id: 'home', label: 'Home Services' },\n  { id: 'car', label: 'Car Detailing' },\n  { id: 'laundry', label: 'Laundry' },\n]\n\n` +
    `// booking-form catalog: one row per service, \`key\` is unique across tabs\n` +
    `export const CATALOG = [...SERVICES.home, ...SERVICES.car, ...SERVICES.laundry].map(({ key, name, cat, price }) => ({ key, name, cat, price }))\n`
)

const site = {
  TRUST: D.trust.map((t) => ({ ...t, img: img(t.img) })),
  SVC_TEXT: D.svcText,
  SLIDES: D.slides.map((s) => ({ ...s, img: img(s.img) })),
  STEPS: D.steps,
  FAQS: D.faqs,
  REVIEWS: D.reviews.map((r) => ({ ...r, img: img(r.img) })),
  CONTACTS: D.contacts.map((c) => ({ ...c, img: img(c.img) })),
  COUNTERS: D.counters,
  FOOTER_SERVICES: D.footerServices,
}
fs.writeFileSync(
  path.join(ROOT, 'src', 'data', 'site.js'),
  banner + Object.entries(site).map(([k, v]) => `export const ${k} = ${json(v)}\n`).join('\n')
)
console.log('services:', Object.fromEntries(Object.entries(services).map(([k, v]) => [k, v.length])), '| site keys:', Object.keys(site).join(','))
